### PR TITLE
 (kickstart_boot+data_by-id_wip) tweaks to support BTS CCS nodes

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Review by glennmorris — APPROVED** [review]
Looks good to me, thanks.

**Review by cbarria — APPROVED** [review]
Looks Great 👍🏻 thanks for fixing those!

**Review by dtapiacl — COMMENTED** [review]
Looks good to me.

**Review by dtapiacl — COMMENTED** [review]
Looks good, i don't see any problems with the changes.

**Pull request merged**
